config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  namespace :admin do
    resources :users
  end
  resources :tasks
  resources :sessions
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labelings, dependent: :destroy
  has_many :tasks, through: :labelings
end

app/models/labeling.rb
class Labeling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :deadline, presence: true
  validates :status, presence: true
  validates :priority, presence: true
  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings

  enum priority: {高:0, 中:1, 低:2}
  scope :title_search, -> (title) {where("title LIKE ?", "%#{title}%")}
  scope :status_search,  -> (status) {where(status: status)}
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :email, uniqueness: true
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, on: :new , length: { minimum: 6 }
  has_many :tasks, dependent: :destroy

  before_update :admin_update_restriction?
  before_destroy :admin_destroy_restriction?

  private

  def admin_update_restriction?
    @admin_user = User.where(admin: true)
    if (@admin_user.count == 1 && @admin_user.first == self) && !(self.admin?)
      throw :abort
    end
  end


  def admin_destroy_restriction?
    if User.where(admin: true).count <=1 && self.admin == true
      throw :abort
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :if_not_admin, only: [ :index, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  def index
    @users = User.all.includes(:tasks).all.order(created_at: :desc)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to admin_user_path(@user.id), notice: "ユーザーを作成しました"
    else
      render :new
    end
  end

  def show
    @tasks = @user.tasks
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path(@user), notice:"ユーザー「#{@user.name}」を編集しました"
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice:"ユーザー「#{@user.name}」を削除しました"
    else
      redirect_to admin_users_path, notice:"ユーザー「#{@user.name}」を削除できません"
    end
  end

  private

  def if_not_admin
    unless current_user.admin?
      flash[:notice] = 'あなたは管理者ではありません'
      redirect_to root_path
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :admin)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :set_task, only: [:show, :edit, :update, :destroy]
before_action :require_login

  def index
    if params[:sort_expired]
      @tasks = current_user.tasks.order(deadline: :desc).page(params[:page]).per(10)
    elsif params[:sort_priority]
      @tasks = current_user.tasks.order(priority: :asc).page(params[:page]).per(10)
    else
      @tasks = current_user.tasks.order(created_at: :desc).page(params[:page]).per(10)
    end

    if params[:search].present?
      if params[:title].present? && params[:status].present?
        @tasks = Task.title_search(params[:title]).status_search(params[:status]).page(params[:page]).per(10)
      elsif params[:title].present?
        @tasks = Task.title_search(params[:title]).page(params[:page]).per(10)
      elsif params[:status].present?
        @tasks = Task.status_search(params[:status]).page(params[:page]).per(10)
      end
    end

    if params[:label_id].present?
      @tasks = @tasks.joins(:labels).where(labels: { id: params[:label_id] })
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:notice] = "タスクを作成しました！"
      redirect_to tasks_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      flash[:notice] = "タスクを編集しました！"
      redirect_to tasks_path
    else
      render edit
    end
  end

  def destroy
    @task.destroy
    flash[:notice] = "タスクを削除しました！"
    redirect_to tasks_path
  end

  private
  def task_params
    params.require(:task).permit(:title, :content, :deadline, :status, :priority, label_ids: [])
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    unless session[:user_id] == nil
      redirect_to user_path(session[:user_id]), notice: 'すでにユーザーが作成されています'
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user.id), notice: "ユーザーを作成しました"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to tasks_path, notice: '他の人のページへアクセスは出来ません'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def require_login
    redirect_to new_session_path, notice: 'ログインしてください' unless logged_in?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: [:admin, @user], local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/admin/users/edit.html.erb
<div class="view_title">
  <h2>ユーザー編集</h2>
</div>
<br>
<div class="container-fluid">
  <div class="form-group">
    <%=form_with(model: @user, local: true, url:  admin_user_path, method: :patch) do |f| %>
      <div>
        <%= f.label :name, 'ユーザー名' %>
        <%= f.text_field :name %>
      </div>
      <br>
      <div>
        <%= f.label :email, 'メールアドレス'%>
        <%= f.text_field :email %>
      </div>
      <br>
      <div>
        <%= f.label :admin, "管理者権限" %>
        <%= f.check_box(:admin, {}, checked_value = "true", unchecked_value = "false" ) %>
      </div>
      <br>
      <div>
        <%= f.submit '登録する' %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container-fluid">
  <div class="view_title">
    <h2>管理画面　ユーザー一覧</h2>
  </div>
  <br>
<div class="container-fluid">
  <div class="form-group">
    <%= link_to "新規登録", new_admin_user_path , class:"btn btn-primary" %>
    <table class="table">
      <thead>
        <th>id</th>
        <th>名前</th>
        <th>メールアドレス</th>
        <th>登録日</th>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.created_at.strftime("%Y年%m月%d日") %></td>
            <% if user.admin %>
              <td>管理者権限あり</td>
            <% else %>
              <td>管理者権限なし</td>
            <% end %>
            <td><p>タスク数：<%= user.tasks.count %></p></td>
            <td><%= link_to '詳細', admin_user_path(user.id), class: "btn btn-info" %></td>
            <td><%= link_to '編集', edit_admin_user_path(user.id), class: "btn btn-info" %></td>
            <td><%= link_to '削除', admin_user_path(user.id) , class: "btn btn-danger", method: :delete, data: { confirm: '削除してもいいですか？' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'task一覧画面へ', tasks_path %>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="view_title">
  <h2>ユーザー作成</h2>
</div>
<br>
<div class="container-fluid">
  <div class="form-group">
    <%=form_with(model: @user, local: true, url:  admin_users_path, method: :post) do |f| %>
      <div>
        <%= f.label :name, 'ユーザー名' %>
        <%= f.text_field :name %>
      </div>
      <br>
      <div>
        <%= f.label :email, 'メールアドレス'%>
        <%= f.text_field :email %>
      </div>
      <br>
      <div>
        <%= f.label :password, "パスワード" %>
        <%= f.password_field :password %>
      </div>
      <br>
      <div>
        <%= f.label :password_confirmation, "パスワード再入力" %>
        <%= f.password_field :password_confirmation %>
      </div>
      <br>
      <div>
        <%= f.label :admin, "管理者権限" %>
        <%= f.check_box(:admin, {}, checked_value = "true", unchecked_value = "false" ) %>
      </div>
      <br>
      <div>
        <%= f.submit '登録する' %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="view_title">
  <h2>ユーザー詳細画面</h2>
</div>
<div class="container-fluid">
  <div class="form-group">
    <br>
    <p>ユーザー名: <%= @user.name %></p>
    <p>メールアドレス: <%= @user.email %></p>
    <% if @user.admin == true %>
       <p>管理者権限: あり</p>
    <% else %>
      <p>管理者権限： なし</p>
    <% end %>

    <% if @tasks == nil %>
      <p>現在タスクはありません</p>
    <% else %>
      <p>現在のタスク状況</p>
      <% @tasks.each do |task| %>
        <div>
          <p><strong>タイトル：</strong><%= task.title %></p>
        </div>
        <div>
          <p><strong>内容：</strong><%= task.content %></p>
        </div>
        <div>
          <p><strong>終了期限：</strong><%= task.deadline %></p>
        </div>
        <div>
          <p><strong>ステータス：</strong><%= task.status %></p>
        </div>
        <div>
          <p><strong>優先順位：</strong><%= task.priority %></p>
        </div>
        <br>
      <% end %>
    <% end %>
    <%= link_to "管理画面へ", admin_users_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <br>
    <div class="log_tags">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <% if logged_in? %>
        <%= link_to "Profile", user_path(current_user.id) %>
        <%= link_to "Logout", session_path(current_user.id), method: :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_path %>
        <%= link_to "Login", new_session_path %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="container-fluid">
  <div class="form-group">
    <%= form_with(model: @task, local: true) do |form| %>
      <% if @task.errors.any? %>
        <div id="error_explanation">
          <h2><%= @task.errors.count %>件のエラーがあります。</h2>
          <ul>
          <% @task.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="task_title">
        <%= form.label :title, "タスク名" %>
        <%= form.text_field :title %>
      </div>
      <br>
      <div class="task_content">
        <%= form.label :content, "タスク詳細" %>
        <%= form.text_field :content %>
      </div>
      <br>
      <div class="task_deadline">
        <%= form.label :deadline, "終了期限"%>
        <%= form.date_field :deadline %>
      </div>
      <br>
      <div class="task_status">
        <%= form.label :status, "状態" %>
        <%= form.select :status, {未着手:"未着手",着手中:"着手中",完了:"完了"}, include_blank: "選択して下さい" %>
      </div>
      <br>
      <div class="task_status">
        <%= form.label :priority, "優先順位" %>
        <%= form.select :priority, {高:"高",中:"中",低:"低"}, include_blank: "選択して下さい" %>
      </div>
      <br>
      <div class="task_label">
        <%= form.label :label, "タスクにラベルをつけてみよう↓↓" %>
        <br>
        <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
      </div>
      <br>
      <%= form.submit name="登録する" %>
    <% end %>
    <br>
    <%= link_to 'task一覧画面に戻る', tasks_path %>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="view_title">
  <h2>タスクを編集する</h2>
</div>
<br>
<%= render 'form'%>

app/views/tasks/index.html.erb
<div class="container-fluid">
  <div class="view_title">
    <h1>task一覧</h1>
  </div>
  <p class="notice"><%= notice %></p>
  <br>

  <div class="form-group">
    <%= form_with(url:tasks_path, local: true, method: :get) do |form| %>
      <%= form.label :title_search, "タイトル検索" %>
      <%= form.text_field :title %>
      <%= form.label :status_search, "状態検索" %>
      <%= form.select :status, {未着手:"未着手",着手中:"着手中",完了:"完了"}, include_blank: "選択して下さい" %>
      <%= form.label :label_id_search, "ラベル絞込" %>
      <%= form.select("label_id", Label.all.pluck(:name, :id), { include_blank:"選択する",include_hidden: false }) %>
      <%= form.hidden_field :search, value:"true" %>
      <%= form.submit name="検索する" %>
    <% end %>

    <br>
    <%= link_to "終了期限でソートする", tasks_path(sort_expired: "true"), class:"btn btn-primary" %>
    <%= link_to "優先順位でソートする", tasks_path(sort_priority: "true"), class:"btn btn-primary " %>
    <%= link_to "元に戻す", tasks_path, class:"btn btn-primary " %>
    <br>
    <br>
  </div>

  <table class="PostTable">
    <tr>
      <th>タスク名</th>
      <th>タスク詳細</th>
      <th>終了期限</th>
      <th>状態</th>
      <th>優先順位</th>
    </tr>
  <% @tasks.each do |task| %>
    <tr>
      <td class="task_row"><%= task.title %></td>
      <td><%= task.content %></td>
      <td class="task_deadline"><%= task.deadline.strftime("%Y年%m月%d日")%></td>
      <td class><%= task.status %></td>
      <td class="task_priority"><%= task.priority %></td>
      <td><%= link_to '詳細', task_path(task.id) , class: "btn btn-info"%></td>
      <td><%= link_to "編集", edit_task_path(task.id), class: "btn btn-info" %></td>
      <td><%= link_to '削除', task_path(task.id), class: "btn btn-danger", method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
      <td class="task_label">
        <% task.labels.each do |label| %>
          <label class='btn-sticky'><%= label.name  %></label>
        <% end %>
      </td>
    </tr>
  <% end %>
  </table>

  <div class="link_group">
    <br>
    <%= paginate @tasks %>
    <br>
    <%= link_to '新しくタスクを投稿する', new_task_path %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="view_title">
  <h2>タスクを作成する</h2>
</div>
<br>
<%= render 'form'%>

app/views/tasks/show.html.erb
<div class="container-fluid">
  <div class="view_title">
    <h2>タスク詳細画面</h2>
  </div>
  <div class="show_style">
    <p>タスク名: <%= @task.title %></p>
    <p>タスク詳細: <%= @task.content %></p>
    <p>終了期限：<%= @task.deadline.strftime("%Y年%m月%d日") if @task.deadline.present? %></p>
    <p class="btn-sticky">
      <% @task.labels.each do |label| %>
        <%= label.name %>
      <% end %>
    </p>
    <br>
    <%= link_to 'task一覧画面に戻る', tasks_path %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container-fluid">
  <div class="view_title">
    <h1>Sign up</h1>
  </div>
  <div class="new_style">
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_with(model: @user, local: true) do |f| %>
    <div class="user_name">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
      <br>
    <div class="user_email">
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
      <br>
    <div class="user_password">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
      <br>
    <div class="user_password_confirmation">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
      <br>
      <%= f.submit "登録する" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="view_title">
    <h2><%= @user.name %>のページ</h2>
  </div>
  <div class="show_style">
    <p>メールアドレス: <%= @user.email %></p>
    <%= link_to 'task一覧画面へ', tasks_path %>
  </div>
</div>